services:
  db_mongo:
    container_name: ${MONGODB_CONTAINER_NAME}
    image: mongo:8.0.0
    volumes:
      - management_system_vol:/data/db
    restart: always
    ports:
      - 27017:27017

volumes:
  management_system_vol:
    external: false
