import type { Metadata } from "next";

import "./globals.css";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div style={{
        backgroundImage: "url('https://www.womgp.com/blog/wp-content/uploads/2020/12/creatividad-empresarial.jpg')",
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        minHeight: '100vh', 
      }}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        </div>
      </body>
    </html>
  );
}
